apiVersion: v1
kind: Template
metadata:
  name: telegraf
  annotations:
     description: telegraf template for openshift
     tags: "monitoring,application metrics"
parameters:
- description: Image name for Telegraf
  displayName: Telegraf image Name
  name: TELEGRAF_IMAGE_NAME
  value: telegraf
- description: Tag version for Telegraf
  displayName: Telegraf Version
  name: TELEGRAF_IMAGE_TAG
  value: 1.12.1
- description: Replacing the value with the namespace that influexdb is running on provide correct DNS name for connection of telegraf with influexdb
  displayName: Replace value with namespace that influexdb is running on
  name: NAMESPACE
  value: influxdb
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: telegraf-enc-dec-forecast
  data:
    telegraf.conf: |
      [[outputs.influxdb]]
        urls = ["http://influxdb.influxdb.svc.cluster.local:8086" ]
        namepass = ["prediction_topic"]
        tagexclude = ["host"]
        database = "Forecast"
        skip_database_creation = false
        database_tag = "prediction_topic"
        timeout = "100s"
      [[inputs.kafka_consumer]]
        name_override = "prediction_topic"
        brokers = ["kafka-svc.msgbus:9093"]
        topics = ["forecast_model2_prediction_topic"]
        consumer_group = "ts_db_3"
        offset = "oldest"
        max_message_len = 1000000
        json_time_key = "time"
        json_time_format = "2006-01-02 15:04:05"
        data_format = "json"
        tag_keys=["pm_name"]
        json_string_fields = ["pm_name"]
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: telegraf-enc-dec-forecast
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: telegraf
        type: ts
    template:
      metadata:
        labels:
          app: telegraf
          type: ts
      spec:
        containers:
        - env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: HOST_PROC
            value: /rootfs/proc
          - name: HOST_SYS
            value: /rootfs/sys
          image: ${TELEGRAF_IMAGE_NAME}:${TELEGRAF_IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          name: telegraf
          resources:
            limits:
              cpu: "1"
              memory: 2G
            requests:
              cpu: 300m
              memory: 2G
          volumeMounts:
          - mountPath: /rootfs/sys
            name: sys
            readOnly: true
          - mountPath: /rootfs/proc
            name: proc
            readOnly: true
          - mountPath: /var/run/docker.sock
            name: docker-socket
          - mountPath: /var/run/utmp
            name: varrunutmp
            readOnly: true
          - mountPath: /var/log
            name: varlog
            readOnly: true
          - mountPath: /var/lib/docker/containers
            name: varlibdockercontainers
            readOnly: true
          - mountPath: /etc/telegraf
            name: config
            readOnly: true
        volumes:
        - hostPath:
            path: /sys
            type: ""
          name: sys
        - hostPath:
            path: /var/run/docker.sock
            type: ""
          name: docker-socket
        - hostPath:
            path: /proc
            type: ""
          name: proc
        - hostPath:
            path: /var/run/utmp
            type: ""
          name: varrunutmp
        - hostPath:
            path: /var/log
            type: ""
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
            type: ""
          name: varlibdockercontainers
        - configMap:
            defaultMode: 420
            name: telegraf-enc-dec-forecast
          name: config