apiVersion: v1
kind: Template
metadata:
  name: schedule-models-ui
parameters:
- description: userinterface
  displayName: userinterface
  name: DOCKER_FONTEND_IMAGE_NAME
  value:

- description: NFS SERVER
  displayName: userinterface
  name: NFS_SERVER
  value: 

objects:       
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: schedule-models-ui
  spec:
    selector:
      matchLabels:
        app: schedule-models-ui
    replicas: 1
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: schedule-models-ui
      spec:
        containers: 
          - image: ${DOCKER_FONTEND_IMAGE_NAME}
            name: schedule-models-ui
            imagePullPolicy: Always
            ports:
            - containerPort: 80
            volumeMounts:
            - name: schedule-models-ui
              mountPath: /usr/share/nginx/html/assets/configs
        volumes:
          - name: schedule-models-ui
            configMap:
              name: schedule-models-ui
  


  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: schedule-models-ui
    creationTimestamp: null
  spec:
    selector:
      app: schedule-models-ui
    type: NodePort
    ports:
    - nodePort: 30219
      port: 80
      protocol: TCP
      targetPort: 80
  status:
    loadBalancer: {} 
  
# Note : SOCKET_SCHEDULER_EXP_TIME is in minutes [ 60 to 4320 (3 days) | recommended : 360 ]
# Note : In EL_URL replace modelName value with '_vaxModelNamevax_' for dynamizing the url in UI
# Note : In FORECAST_GRAFANA_URL replace data Id value with '_vax_var-PM_name_vax_' for dynamizing the url in UI
- apiVersion: v1
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: schedule-models-ui
  
  data:
    angular_conf.json: |
     {  
      "ANOMALY_POD":"http://167.254.204.64:32203",
      "SCHEDULER_POD":"http://167.254.204.64:30189",
      "DATAINSIGHT_POD":"http://167.254.204.64:31017",
      "ANOMALY_SOCKET":"http://167.254.204.64:32203/socket",
      "ANOMALY_PROFILER":"anomaly_profiler*",
      "SOCKET_SCHEDULER_EXP_TIME":360,
      "EL_POD":"https://167.254.204.64:32101",
      "EL_URL":"/app/dashboards#/view/093906e0-6d22-11eb-933b-df15118cab21?embed=true&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-90d,to:now))&_a=(description:'',filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'7eea5f80-37ff-11ec-b2c6-d391a8caeaa7',key:pm_alm.modelName,negate:!f,params:(query:'_vaxModelNamevax_'),type:phrase),query:(match_phrase:(pm_alm.modelName:'_vaxModelNamevax_')))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!f,title:'Loss%20Histogram',viewMode:view)&hide-filter-bar=true",
      "DEFAULT_NAME":"fujitsu",
      "DEFAULT_PASSWORD":"fujitsu",
      "CONFIG_MAP": "true"
      }