export const ANOMALY_URLS = {
    PUT_UPDATE_ANOMALYMODEL_CONFIG_API: '/api/anomaly/v1/modelconfigs/',
    POST_SAVE_ANOMALYMODEL_CONFIG_API: '/api/anomaly/v1/modelconfigs/',
    GET_ANMDETECTION_TABLE_DATA_API: '/api/anomaly/v1/trainings/completed/all',
    GET_ANMDETECTION_MODEL_TR_DETAILS_API: '/api/anomaly/v1/trainings/',
    GET_ANMDETECTION_MODEL_ANMD_DETAILS_API: '/api/anomaly/v1/anomalydetection/',
    GET_ANM_TABLE_DATA_API: '/api/anomaly/v1/anomalies/anomalies*/',
    GET_ANM_MODEL_DETAILS_API: '/api/anomaly/v1/allmodelsdetails/',
    GET_ALLTASK_DATA_API: '/api/scheduler/v1/custom-schedule',
    GET_ANOMALY_MODEL_CONFIG: '/api/anomaly/v1/modelconfigs/',
    GET_ANOMALY_MODEL_CONFIG_USING_NAME: '/api/anomaly/v1/modelconfigs/',
    DELETE_ANOMALY_MODEL_CONFIG: '/api/anomaly/v1/modelconfigs/',
    GET_ANOMALY_MODEL_CONFIGURATIONS_API: '/api/anomaly/v1/configurationformodelconfig/MODELI',
    GET_SCHEDULE_DETAILS : '/api/scheduler/v1/schedule/',
    GET_TRAINED_MODELS : '/api/anomaly/v1/trainings/completed/',
    GET_TRAINING_STATUS : '/api/anomaly/v1/trainings/running/',
    DELETE_TRAINED_MODELS : '/api/anomaly/v1/trainings',
    POST_CREATE_TASK_API : '/api/scheduler/v1/schedule/',
    PUT_UPDATE_TASK_API : '/api/scheduler/v1/schedule/',
    ACTION_ON_TASK : '/api/scheduler/v1/schedule/actions/',
    GET_DATA_SOURCE_DETAILS_API: '/datasource/api/getDataSource',
    POST_SCHEDULE_DETECT_ANOMALY_API: '/api/anomaly/v1/anomalydetection',
    GET_DATASET_LIST: '/datasource/api/getDataSet',
    POST_ANOMALY_SCHEDULE_PROFILING_API: '/api/anomaly/v1/anomalies/profiling',
    GET_ANOMALY_PROFILING_RESULT_API: '/api/anomaly/v1/anomalies/',
    POST_DATAINSIGHT_DATAPREVIEW_API: '/datasource/api/getDataPreview',
    DELETE_STOP_TRAINEDMODEL_API: '/api/anomaly/v1/trainings/running',
    DELETE_STOP_ANOMALYDETECTION_API: '/api/anomaly/v1/anomalydetection',
    GET_ANOMALY_DATASETS: 'getAnomalyDataSets/',
    GET_ANOMALY_DATASET_FEATURES_API: 'getAnomalyDataSetFeatures/',
    GET_MODEL_CONFIG_LISTS:'/api/v1/modelconfigs'
};


