// export const DATAMANAGEMENT_URLS = {
//     GET_DATAINSIGHT_JOBTYPE_API: 'getJobTypeList/',
//     GET_DATAINSIGHT_PROPERTYTYPE_API: 'getPropertyTypeList/',
//     POST_DATAINSIGHT_DATAPREVIEW_API: 'getDataPreviewDetails/',
//     GET_DATAINSIGHT_CONFIGURATION_API: 'getConfigurationList/',
//     GET_DATAINSIGHT_CONFIGDET_API: 'getConfigurationDet/',
//     POST_DATAINSIGHT_STEPS_API: 'getStepsDetails/',
//     POST_DATAINSIGHT_FETCH_FEATURES_API: 'getFeatureDet/',
//     POST_DATAINSIGHT_CREATE_DATA_SET_API: 'createDataSet/',
//     PUT_DATAINSIGHT_UPDATE_DATA_SET_API: 'updateDataSet/',
//     POST_DATAINSIGHT_FILE_UPLOAD_API: 'fileUploadDataSet/',
//     POST_DATAINSIGHT_STREAM_SCHEDULE_API: 'streamDataSchedule/',
//     GET_DATAINSIGHT_STREAM_SCHEDULE_API: 'getStreamScheduleStatus/',
//     GET_CONFIGURATION_TABLEVIEW_API: 'getConfigurationTableview/',
//     GET_CONFIGURATION_DETAILEDVIEW_API: 'getConfigurationDetailedView/',
//     GET_CONFIGURATION_DBTYPE_API: 'getConfigurationDBType/',
//     CREATE_CONFIGURATION_API: 'createConfiguration/',
//     CREATE_NEWDBYTYPE_API: 'createNewDBType/',
//     GET_DATA_SOURCE_LIST_API: 'getDataSourceList/',
//     GET_DATA_SOURCE_DETAILS_API: 'getDataSource/',
//     DELETE_DATA_SOURCE_API: 'deleteDataSource/',
//     DELETE_CONFIGURATION: 'deleteConfiguration/',
//     UPDATE_CONFIGURATION: 'updateConfiguration/'
// };


export const DATAMANAGEMENT_URLS = {
    GET_DATAINSIGHT_JOBTYPE_API: '/datasource/api/jobType',
    GET_CONFIGURATION_TABLEVIEW_API: '/configuration/api/configuration',
    GET_CONFIGURATION_DETAILEDVIEW_API: '/configuration/api/getConfiguration',
    CREATE_CONFIGURATION_API: '/configuration/api/configuration',
    CREATE_NEWDBYTYPE_API: '/configuration/api/dbType',
    DELETE_CONFIGURATION: '/configuration/api/configuration',
    GET_CONFIGURATION_DBTYPE_API: '/configuration/api/dbType',
    GET_DATA_SOURCE_LIST_API: '/datasource/api/dataSource',
    GET_EMAIL_RULES_API: '/notification/api/emailRules',
    CREATE_EMAIL_RULES_API: '/notification/api/emailRules',
    UPDATE_EMAIL_RULES_API : '/notification/api/emailRules',
    DELETE_EMAIL_RULES_API: '/notification/api/emailRules',
    GET_DATA_SOURCE_DETAILS_API: '/datasource/api/getDataSource',
    DELETE_DATA_SOURCE_API: '/datasource/api/dataSource',
    GET_DATAINSIGHT_CONFIGURATION_API: '/configuration/api/configuration',
    GET_DATAINSIGHT_CONFIGDET_API: '/configuration/api/getConfiguration',
    GET_DATAINSIGHT_PROPERTYTYPE_API: '/datasource/api/propertyType',
    POST_DATAINSIGHT_DATAPREVIEW_API: '/datasource/api/getDataPreview',
    POST_DATAINSIGHT_STEPS_API: '/configuration/api/getDataSourceDetails',
    POST_DATAINSIGHT_FETCH_FEATURES_API: '/configuration/api/getFetchFeatures',
    POST_DATAINSIGHT_CREATE_DATA_SET_API: '/datasource/api/dataSource',
    PUT_DATAINSIGHT_UPDATE_DATA_SET_API: '/datasource/api/dataSource',
    POST_DATAINSIGHT_FILE_UPLOAD_API: '/datasource/api/postFile',
    POST_DATAINSIGHT_STREAM_SCHEDULE_API: '/podutils/api/postScheduleMessage',
    GET_DATAINSIGHT_STREAM_SCHEDULE_API: '/podutils/api/getScheduleMessage',
    UPDATE_CONFIGURATION: '/configuration/api/configuration',
    GET_DATAINSIGHT_CONFIGURATION_NAMES_API: '/configuration/api/getConfigurationNamesList',
    GET_SERVERCONFIGURATION_API:'/api/notification-management/v1/notification/file/read/emailprop',
    PUT_SERVERCONFIGURATION_API:'/api/notification-management/v1/notification/file/update/emailprop'
};
