apiVersion: v1 
kind: Template 
metadata: 
  name: classification-microservice
parameters:

- description: classification-microservice
  displayName: classification-microservice
  name: DOCKER_IMAGE
  value: fnc-docker-reg:3000/vax/classification:v1.0

objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: classification-microservice
    labels:
      draft: classification-microservice-app
      chart: "classification-microservice"
  spec:
    selector:
      matchLabels:
        app: classification-microservice
    replicas: 1
    minReadySeconds: 120
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    template:
      metadata:
        labels:
          draft: classification-microservice-app
          app: classification-microservice
      spec:
        containers:
        - name: classification-microservice
          image: ${DOCKER_IMAGE}
          imagePullPolicy: Always
          env:
          envFrom: 
          ports:
          - containerPort: 8080
          - containerPort: 443
          resources:
              limits:
                cpu: 2
                memory: 4Gi
              requests:
                cpu: 1
                memory: 2Gi
        terminationGracePeriodSeconds: 
- apiVersion: v1
  kind: Service
  metadata:
    name: classification-microservice
    labels:
      chart: "classification-microservice"
    annotations:
      fabric8.io/expose: "true"
      fabric8.io/ingress.annotations: 'kubernetes.io/ingress.class: nginx'
  
  spec:
    type: NodePort
    ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31126
      protocol: TCP
      name: http
    - port: 443
      nodePort: 31004
      protocol: TCP
      name: https
    selector:
      app: classification-microservice
  