apiVersion: v1 
kind: Template 
metadata: 
  name: modelandexecutions-ms
parameters:

- description: training scheduler for schedule the jobs for training, monitoring the training status for optical app.
  displayName: modelandexecutions-ms
  name: DOCKER_REGISTRY
  value: 

- description: training scheduler for schedule the jobs for training, monitoring the training status for optical app.
  displayName: modelandexecutions-ms
  name: DOCKER_IMAGE_NAME
  value: 

- description: training scheduler for schedule the jobs for training, monitoring the training status for optical app.
  displayName: modelandexecutions-ms
  name: DOCKER_IMAGE_TAG
  value: 

objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: modelandexecutions-ms
    labels:
      draft: modelandexecutions-ms-app
      chart: "modelandexecutions-ms"
  spec:
    selector:
      matchLabels:
        app: modelandexecutions-ms
    replicas: 1
    template:
      metadata:
        labels:
          draft: modelandexecutions-ms-app
          app: modelandexecutions-ms
      spec:
        containers:
        - name: modelandexecutions-ms
          image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
          imagePullPolicy: Always
          env:
          envFrom: 
          ports:
          - containerPort: 8080         
          resources:
              limits:
                cpu: 800m
                memory: 3Gi
              requests:
                cpu: 500m
                memory: 1Gi
        terminationGracePeriodSeconds: 
- apiVersion: v1
  kind: Service
  metadata:
    name: modelandexecutions-ms
    labels:
      chart: "modelandexecutions-ms"
    annotations:
      fabric8.io/expose: "true"
      fabric8.io/ingress.annotations: 'kubernetes.io/ingress.class: nginx'
  
  spec:
    type: NodePort
    ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32203
      protocol: TCP
      name: http
    selector:
      app: modelandexecutions-ms
  
