apiVersion: v1 
kind: Template 
metadata: 
  name: scheduler-microservice
parameters:

- description: training scheduler for schedule the jobs for training, monitoring the training status for optical app.
  displayName: scheduler-microservice
  name: DOCKER_IMAGE
  value: fnc-docker-reg:3000/scheduler:met1.0

objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: scheduler-microservice
    labels:
      draft: scheduler-microservice-app
      chart: "scheduler-microservice"
  spec:
    selector:
      matchLabels:
        app: scheduler-microservice
    replicas: 1
    minReadySeconds: 120
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    template:
      metadata:
        labels:
          draft: scheduler-microservice-app
          app: scheduler-microservice
      spec:
        containers:
        - name: scheduler-microservice
          image: ${DOCKER_IMAGE}
          imagePullPolicy: Always
          env:
          envFrom: 
          ports:
          - containerPort: 8002
          resources:
              limits:
                cpu: 2
                memory: 4Gi
              requests:
                cpu: 1
                memory: 2Gi
        terminationGracePeriodSeconds: 
- apiVersion: v1
  kind: Service
  metadata:
    name: scheduler-microservice
    labels:
      chart: "scheduler-microservice"
    annotations:
      fabric8.io/expose: "true"
      fabric8.io/ingress.annotations: 'kubernetes.io/ingress.class: nginx'
  
  spec:
    type: NodePort
    ports:
    - port: 8002
      targetPort: 8002
      nodePort: 30189
      protocol: TCP
      name: http
    selector:
      app: scheduler-microservice
  