apiVersion: v1
kind: Template
metadata:
  name: forecast-ui
parameters:
- description: userinterface
  displayName: userinterface
  name: DOCKER_FONTEND_IMAGE_NAME
  value:

- description: NFS SERVER
  displayName: userinterface
  name: NFS_SERVER
  value: 

objects:       
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: forecast-ui
  spec:
    selector:
      matchLabels:
        app: forecast-ui
    replicas: 1
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: forecast-ui
      spec:
        containers: 
          - image: ${DOCKER_FONTEND_IMAGE_NAME}
            name: forecast-ui
            imagePullPolicy: Always
            ports:
            - containerPort: 80
            volumeMounts:
            - name: forecast-ui
              mountPath: /usr/share/nginx/html/assets/configs
        volumes:
          - name: forecast-ui
            configMap:
              name: forecast-ui

  

  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: forecast-ui
    creationTimestamp: null
  spec:
    selector:
      app: forecast-ui
    type: NodePort
    ports:
    - nodePort: 30293
      port: 80
      protocol: TCP
      targetPort: 80
  status:
    loadBalancer: {} 
  
# Note : SOCKET_SCHEDULER_EXP_TIME is in minutes [ 60 to 4320 (3 days) | recommended : 360 ]
# Note : In EL_URL replace modelName value with '_vaxModelNamevax_' for dynamizing the url in UI
# Note : In FORECAST_GRAFANA_URL replace data Id value with '_vax_var-PM_name_vax_' for dynamizing the url in UI
- apiVersion: v1
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: forecast-ui
  
  data:
    angular_conf.json: |
     {  
      "FORECAST_POD":"http://167.254.204.64:30920",
      "FORECAST_GRAFANA_URL":"http://167.254.204.64:32300/d/CijHdYGMk/pm_forcast_1?orgId=1&orderId=1&var-PM_name=_vax_var-PM_name_vax_&kiosk=tv&refresh=5s",
      "SCHEDULER_POD":"http://167.254.204.64:30189",
      "DATAINSIGHT_POD":"http://167.254.204.64:31017",
      "FORECAST_SOCKET":"http://167.254.204.64:30920/socket",
      "SOCKET_SCHEDULER_EXP_TIME":360,
      "DEFAULT_NAME":"fujitsu",
      "DEFAULT_PASSWORD":"fujitsu",
      "CONFIG_MAP": "true"
      }