apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
spec:
  selector:
    matchLabels:
      app: angular
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: angular
    spec:
      containers: 
        - image: 42402112/sumit2112:latest
          name: angular
          imagePullPolicy: Always
          ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: angular
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
  type: NodePort