apiVersion: v1
kind: Template
metadata:
  name: correlation-ui
parameters:
- description: userinterface
  displayName: userinterface
  name: DOCKER_FONTEND_IMAGE_NAME
  value:

- description: NFS SERVER
  displayName: userinterface
  name: NFS_SERVER
  value: 

objects:       
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: correlation-ui
  spec:
    selector:
      matchLabels:
        app: correlation-ui
    replicas: 1
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: correlation-ui
      spec:
        containers: 
          - image: ${DOCKER_FONTEND_IMAGE_NAME}
            name: correlation-ui
            imagePullPolicy: Always
            ports:
            - containerPort: 80
            volumeMounts:
            - name: correlation-ui
              mountPath: /usr/share/nginx/html/assets/configs
        volumes:
          - name: correlation-ui
            configMap:
              name: correlation-ui
  


  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: correlation-ui
    creationTimestamp: null
  spec:
    selector:
      app: correlation-ui
    type: NodePort
    ports:
    - nodePort: 30295
      port: 80
      protocol: TCP
      targetPort: 80
  status:
    loadBalancer: {} 

# Note : SOCKET_SCHEDULER_EXP_TIME is in minutes [ 60 to 4320 (3 days) | recommended : 360 ]
# Note : In EL_URL replace modelName value with '_vaxModelNamevax_' for dynamizing the url in UI
# Note : In FORECAST_GRAFANA_URL replace data Id value with '_vax_var-PM_name_vax_' for dynamizing the url in UI
- apiVersion: v1
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: correlation-ui
  
  data:
    angular_conf.json: |
     {  
      "CORRELATION_POD":"http://167.254.204.64:30065",
      "DATAINSIGHT_POD":"http://167.254.204.64:31017",
      "DEFAULT_NAME":"fujitsu",
      "DEFAULT_PASSWORD":"fujitsu",
      "CONFIG_MAP": "true"
      }  