apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T18:52:05Z
  name: "asctraining"
  labels:
    chart: "asctraining"
  #namespace:      {{ .Values.configMap.namespace }}
  #labels:         <none>
  #annotations:    <none>

data:
  alarmstormclassification.conf: |
    [elasticsearch]
    elkServer = elasticsearch.elk.svc
    elkPort = 9200
    index = cluster_alarms

    [kafka]
    kafkaServer     = kafka-svc.msgbus.svc
    kafkaPort       = 9093
    producer_topic  = trainingstatus
    train_topic     = classificationTrainDB
    statusTopic     = TES_POD_STATUS
    dataFormat      = Json

    [mongo]
    mongoUrl = mongo-node-1.database.svc:27017,mongo-node-2.database.svc:27017,mongo-node-3.database.svc:27017
    mongoDb  = alarmStormClassification
    mongoCol = modelconfiguration

    [classification]
    scalerFileNamePostFix        = _scaler.p
    pcaModelFileNamePostfix      = _dim.sav
    kmeansModelFileNamePostfix   = _clus.sav
    encoderFileNamePostFix       = _encoder.p
    pcaDirLocation               = /mnt/k8sMount/ml/alarmStorm/training_model/
    encoderDirLocation           = /mnt/k8sMount/ml/alarmStorm/encoder/
    scalerDirLocation            = /mnt/k8sMount/ml/alarmStorm/scaler/
    logFolder                    = /logs
    pattern_url                  = http://167.254.204.64:32203/api/v1/modelconfigs/ASCTRAINING/
    schema_url                   = http://167.254.204.64:31017/datasource/api/getDataSource?dataSetName=
    etl                          = ALARMSTORM CLASSIFICATION
    
    [sequence]
    raw_alarm_column = Alarm Description
    raw_time_column  = EMS Date Time(CDT)
    seq_index        = sequence_index 
