apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T18:52:05Z
  name: "anomalymodel2prediction"
  labels:
    chart: "anomalymodel2prediction"
  #namespace:      {{ .Values.configMap.namespace }}
  #labels:         <none>
  #annotations:    <none>

data:
  anomalymodel2_exec.txt : |
  [CONTROLLER]
  MODEL_ID=modelName
  DATASET=dataSetName
  MODEL_CONFIG=modelConfigName
  THRESHOLD=threshold

  [AM2_EXECUTION]
  PRODUCER_TOPIC=AM2_ANOMOLIES_DB
  MONITOR_TOPIC=executionstatus
  POD_STATUS_TOPIC=TES_POD_STATUS
  AM2_MSE_THRESHOLD=8
  AM2_MSE_EXPONENTS=-2
  BULK_RECORD_SIZE=32
  l_code=PEXEC
  Print=true
  log_dir=/logs/
  SCALER_FILENAME_POSTFIX =_scaler.sav
  MODEL_FILENAME_POSTFIX=_model.sav
  ENCODER_FILENAME_POSTFIX=_encoder.p
  DIR_LOCATION_MODEL=/mnt/k8sMount/ml/anomaly_model2/training_model/
  DIR_LOCATION_ENCODER=/mnt/k8sMount/ml/anomaly_model2/encoder/
  DIR_LOCATION_SCALER=/mnt/k8sMount/ml/anomaly_model2/scaler/

  [INTERFACE]
  KAFKA_SERVER=kafka-svc.msgbus.svc
  KAFKA_SERVER_PORT=9093
  mongo_rs=mongo-node-1.database.svc:27017,mongo-node-2.database.svc:27017,mongo-node-3.database.svc:27017
  mongo_db=anomalyDetection
  mongo_col=anomaly
  jobtype=ANOMALYEXECUTION2

  [MODEL_CONFIG]
  api_endpoint=http://167.254.204.64:32203/api/v1/modelconfigs/ANOMALYTRAINING2/
  schema_url=http://167.254.204.64:31017/datasource/api/getDataSource?dataSetName=
  XFEATURE_LIST=xfeatureList
  UNIQUE_FEATURE=uniqueFeature
  STRING_FEATURES=stringFeatures
  ENCODER=encoder
  SCALER=scaler
  TRAINING_FILTER=trainingFilter
  P_COMPONENT=p_components