// export const ANOMALY_URLS = {
//     PUT_UPDATE_ANOMALYMODEL_CONFIG_API: 'updateAnmMdConfig/',
//     POST_SAVE_ANOMALYMODEL_CONFIG_API: 'createAnmMdConfig/',
//     GET_ANMDETECTION_TABLE_DATA_API: 'getAllAnmdTrainedModels/',
//     GET_ANMDETECTION_MODEL_TR_DETAILS_API: 'getTrainingDetails/',
//     GET_ANMDETECTION_MODEL_ANMD_DETAILS_API: 'getTrainingResultAnomalyDetData/',
//     GET_ANM_TABLE_DATA_API: 'getAllAnmModels/',
//     GET_ANM_MODEL_DETAILS_API: 'getAnmModelDetails/',
//     GET_ALLTASK_DATA_API: 'getalltaskDetails/',
//     GET_ANOMALY_MODEL_CONFIG: 'getAnomalyModelConfigs/',
//     GET_ANOMALY_DATASETS: 'getAnomalyDataSets/',
//     GET_ANOMALY_MODEL_CONFIG_USING_NAME: 'getAnomalyModelConfigUsingName/',
//     DELETE_ANOMALY_MODEL_CONFIG: 'deleteAnomalyModel/',
//     GET_ANOMALY_MODEL_CONFIGURATIONS_API: 'getAnmMdConfigurations/',
//     GET_SCHEDULE_DETAILS : 'getScheduleDetails/',
//     GET_TRAINED_MODELS : 'getTrainedModels/',
//     GET_TRAINING_STATUS : 'getTrainingStatus/',
//     DELETE_TRAINED_MODELS : 'deleteTrainedModels/',
//     POST_CREATE_TASK_API : 'createTask/',
//     PUT_UPDATE_TASK_API : 'updateTask/',
//     ACTION_ON_TASK : 'actionOnTask/',
//     GET_ANOMALY_DATASET_FEATURES_API: 'getAnomalyDataSetFeatures/',
//     GET_DATA_SOURCE_DETAILS_API: 'getDataSource/',
//     POST_SCHEDULE_DETECT_ANOMALY_API: 'scheduleAnmdDetect/',
//     GET_DATASET_LIST: 'getDataSetForJobType/',
//     POST_ANOMALY_SCHEDULE_PROFILING_API: 'scheduleAnmlProfiling/',
//     GET_ANOMALY_PROFILING_RESULT_API: 'anmlProfilingResult/',
//     POST_DATAINSIGHT_DATAPREVIEW_API: 'getDataPreviewDetails/',
//     DELETE_STOP_TRAINEDMODEL_API: 'stopTrainingModel/',
//     DELETE_STOP_ANOMALYDETECTION_API: 'stopAnomalyDetection/',
// };

export const ANOMALY_URLS = {
    PUT_UPDATE_ANOMALYMODEL_CONFIG_API: '/api/v1/modelconfigs/',
    POST_SAVE_ANOMALYMODEL_CONFIG_API: '/api/v1/modelconfigs/',
    GET_ANMDETECTION_TABLE_DATA_API: '/api/v1/trainings/completed/all',
    GET_ANMDETECTION_MODEL_TR_DETAILS_API: '/api/v1/trainings/',
    GET_ANMDETECTION_MODEL_ANMD_DETAILS_API: '/api/v1/execution/',
    GET_ANM_TABLE_DATA_API: '/api/v1/profiling/anomaly/anomalies/',
    GET_ANM_MODEL_DETAILS_API: '/api/v1/allmodelsdetails/',
    GET_ALLTASK_DATA_API: '/api/scheduler/v1/custom-schedule',
    GET_ANOMALY_MODEL_CONFIG: '/api/v1/modelconfigs/',
    GET_ANOMALY_MODEL_CONFIG_USING_NAME: '/api/v1/modelconfigs/',
    DELETE_ANOMALY_MODEL_CONFIG: '/api/v1/modelconfigs/',
    GET_ANOMALY_MODEL_CONFIGURATIONS_API: '/api/v1/configurationformodelconfig',
    GET_SCHEDULE_DETAILS : '/api/scheduler/v1/schedule/',
    GET_TRAINED_MODELS : '/api/v1/trainings/completed/',
    GET_TRAINING_STATUS : '/api/v1/trainings/running/',
    DELETE_TRAINED_MODELS : '/api/v1/trainings',
    POST_CREATE_TASK_API : '/api/scheduler/v1/schedule/',
    PUT_UPDATE_TASK_API : '/api/scheduler/v1/schedule/',
    ACTION_ON_TASK : '/api/scheduler/v1/schedule/actions/',
    GET_DATA_SOURCE_DETAILS_API: '/datasource/api/getDataSource',
    POST_SCHEDULE_DETECT_ANOMALY_API: '/api/v1/execution',
    GET_DATASET_LIST: '/datasource/api/getDataSet',
    POST_ANOMALY_SCHEDULE_PROFILING_API: '/api/v1/profiling/anomaly/schedule/',
    GET_ANOMALY_PROFILING_RESULT_API: '/api/v1/profiling/anomaly/rootcause/',
    POST_DATAINSIGHT_DATAPREVIEW_API: '/datasource/api/getDataPreview',
    DELETE_STOP_TRAINEDMODEL_API: '/api/v1/trainings/running',
    DELETE_STOP_ANOMALYDETECTION_API: '/api/v1/execution',
    GET_ANOMALY_DATASETS: 'getAnomalyDataSets/',
    GET_ANOMALY_DATASET_FEATURES_API: 'getAnomalyDataSetFeatures/',
};


